import '../styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

type Props = {
  children: React.ReactNode;
  panel: React.ReactNode;
};

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: Props) {
  const { children, panel } = props;

  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        {children}
        {panel}
      </body>
    </html>
  );
}
